import Foundation

let root = CommandLine.arguments.dropFirst().first ?? FileManager.default.currentDirectoryPath
let rootURL = URL(fileURLWithPath: root)

func read(_ relativePath: String) throws -> String {
    try String(contentsOf: rootURL.appendingPathComponent(relativePath), encoding: .utf8)
}

func require(_ condition: @autoclosure () -> Bool, _ message: String) {
    if !condition() {
        fputs("digital-human-session-client-check failed: \(message)\n", stderr)
        exit(1)
    }
}

let client = try read("DreamJourney/Sources/Services/DreamJourneyBackendClient.swift")
let authSessionStore = try read("DreamJourney/Sources/Services/BackendAuthSessionStore.swift")
let echo = try read("DreamJourney/Sources/Modules/Echo/EchoViewController.swift")
let appDelegate = try read("DreamJourney/Sources/AppDelegate.swift")
let featureFlags = try read("DreamJourney/Sources/App/FeatureFlagService.swift")
let runtime = try read("DreamJourney/Sources/Services/DigitalHuman/DigitalHumanRuntime.swift")
let runtimeFactory = try read("DreamJourney/Sources/Services/DigitalHuman/DigitalHumanRuntimeFactory.swift")
let releaseRegression = try read("Scripts/QA/prd-stitch-ui/run-release-regression.sh")
let runtimeStubSmoke = try read("Scripts/QA/prd-stitch-ui/run-digital-human-runtime-stub-smoke.sh")
let statusDoc = try read("docs/superpowers/status/2026-06-25-tencent-digital-human-runtime-foundation.md")

require(client.contains("struct DigitalHumanRuntimeCapability"), "runtime capability parser is missing")
require(client.contains("struct DigitalHumanSessionContract"), "session contract model is missing")
require(client.contains("struct DigitalHumanSessionCredential"), "session credential model is missing")
require(client.contains("struct DigitalHumanSessionPolicy"), "session policy model is missing")
require(client.contains("fetchDigitalHumanRuntimeCapability"), "runtime capability fetch helper is missing")
require(client.contains("createDigitalHumanSession("), "create session client method is missing")
require(client.contains("\"/digital-human/sessions\""), "client must call /digital-human/sessions")
require(client.contains("DigitalHumanSessionContract(json:"), "client must parse session contract")
require(client.contains("toDigitalHumanProfile(displayName:"), "session contract must convert to DigitalHumanProfile")
require(client.contains("lifecycleMode: DigitalHumanMode"), "session lifecycle mode must parse to DigitalHumanMode")
require(client.contains("let sdkAdapterLinked: Bool"), "runtime capability should parse SDK adapter readiness")
require(client.contains("let sdkAuthMode: String"), "runtime capability should parse Tencent appkey/accesstoken auth mode")
require(client.contains("let requiredServerEnv: [String]"), "runtime capability should parse required server env")
require(client.contains("let requiredAssetEnv: [String]"), "runtime capability should parse avatar/project asset env")
require(client.contains("let optionalASREnv: [String]"), "runtime capability should parse ASR-only Tencent env")
require(client.contains("let providerFieldAliases: [String]"), "runtime capability should parse official provider field aliases")
require(client.contains("let sdkReadinessMessage: String"), "runtime capability should parse SDK readiness message")
require(client.contains("\"sdkAuthMode\""), "runtime capability should read sdkAuthMode")
require(client.contains("\"requiredAssetEnv\""), "runtime capability should read requiredAssetEnv")
require(client.contains("\"optionalASREnv\""), "runtime capability should read optionalASREnv")
require(client.contains("\"providerFieldAliases\""), "runtime capability should read providerFieldAliases")

require(runtime.contains("DigitalHumanSessionState"), "runtime abstraction must exist")
require(runtimeFactory.contains("makeRuntime(") && runtimeFactory.contains("for contract: DigitalHumanSessionContract"), "runtime factory should create runtime from backend session contract")
require(runtimeFactory.contains("contract.isUsableForClientRuntime"), "runtime factory must reject expired or malformed real session contracts")
require(runtimeFactory.contains("isRealSDKBacked: false"), "runtime factory should not claim real SDK readiness without linked adapter")
require(echo.contains("digitalHumanRuntime: DigitalHumanRuntime?"), "Echo must hold a runtime abstraction")
require(echo.contains("runUIQADigitalHumanRuntimeStubSmoke"), "Echo QA runtime stub smoke is missing")
require(echo.contains("DigitalHumanRuntimeFactory.makeRuntime"), "Echo QA path must consume runtime factory")
require(echo.contains("createDigitalHumanSession("), "Echo QA path must request backend session contract")
require(echo.contains("AudioOnlyDigitalHumanRuntime"), "Echo QA path must verify audio-only fallback")
require(echo.contains("\"subjectKind\": \"self\""), "runtime-stub smoke must use its explicit self-subject eligibility fixture")
require(echo.contains("\"consentPurpose\": \"digitalHuman\""), "runtime-stub smoke must scope its eligibility fixture to digital human only")
require(client.contains("subjectEligibility: [String: Any]? = nil"), "session client must accept explicit eligibility evidence without inventing it for product calls")
require(client.contains("payload[\"subjectEligibility\"] = subjectEligibility"), "session client must forward supplied eligibility evidence")

require(featureFlags.contains("DJRunDigitalHumanRuntimeStubSmoke"), "QA scenario registry launch arg is missing")
require(appDelegate.contains("case .digitalHumanRuntimeStubSmoke"), "AppDelegate scenario dispatch is missing")
require(appDelegate.contains("runDigitalHumanRuntimeStubSmoke"), "AppDelegate runner is missing")
require(featureFlags.contains("enum QAEchoScenarioRunner"), "runtime-stub route should use the compile-isolated shared Echo scenario runner")
require(appDelegate.contains("smokeName: \"DigitalHumanRuntimeStubSmoke\""), "runtime-stub route should retain its stable shared-runner smoke label")
require(appDelegate.contains("prepareUIQADigitalHumanRuntimeStubBackendSession"), "runtime-stub route must establish a QA-only authenticated backend session")
require(appDelegate.contains("createIdentityChallenge(phone:"), "runtime-stub auth fixture must use the V2 challenge flow")
require(appDelegate.contains("verifyIdentityChallenge("), "runtime-stub auth fixture must verify the V2 challenge")
require(appDelegate.contains("activateUIQADigitalHumanRuntimeStubAccount"), "runtime-stub auth fixture must activate the verified account lease")
require(appDelegate.contains("AccountSessionActor.shared.activateVerifiedLogin"), "runtime-stub auth fixture must publish a verified AccountSessionActor lease")
require(appDelegate.contains("writeDigitalHumanRuntimeStubSmokeResult"), "AppDelegate result writer is missing")
require(appDelegate.contains("digital-human-runtime-stub-smoke-result.json"), "QA result file name is missing")

require(runtimeStubSmoke.contains("DJRunDigitalHumanRuntimeStubSmoke"), "runtime stub smoke must launch the QA harness")
require(runtimeStubSmoke.contains("STORE_BACKEND=memory"), "runtime stub smoke must start an isolated memory backend")
require(runtimeStubSmoke.contains("IDENTITY_CHALLENGE_ADAPTER=synthetic"), "runtime stub smoke must use only a local synthetic V2 identity fixture")
require(runtimeStubSmoke.contains("DJUIQAIdentityChallengeCode="), "runtime stub smoke must pass the local synthetic challenge code through the QA launch boundary")
require(runtimeStubSmoke.contains("UIQA_DIGITAL_HUMAN_RUNTIME_STUB=1"), "runtime stub smoke must mark its isolated backend process explicitly")
require(runtimeStubSmoke.contains("visible_features.add(\"digitalHumanLivePanel\")"), "runtime stub smoke must scope its temporary policy allowance to the digital-human fixture")
require(runtimeStubSmoke.contains("production policy remains closed to this feature by default"), "runtime stub smoke must document that its policy allowance is process-local only")
require(runtimeStubSmoke.contains("scopedBrokerRequired"), "runtime stub smoke must assert the scoped broker stop condition")
require(runtimeStubSmoke.contains("blockedUntilScopedBroker"), "runtime stub smoke must keep the provider blocked without a scoped broker")
require(runtimeStubSmoke.contains("runtimeIsRealSDKBacked"), "runtime stub smoke must assert SDK is not falsely marked real")
require(runtimeStubSmoke.contains("fallbackMode") && runtimeStubSmoke.contains("textOnly"), "runtime stub smoke must assert text-only fallback")
require(authSessionStore.contains("CFGetTypeID(number) != CFBooleanGetTypeID()"), "auth session integer parser must distinguish JSON numbers from booleans")
require(authSessionStore.contains("#if UI_QA_SIMULATOR && targetEnvironment(simulator)"), "QA-only ephemeral auth fallback must be compile-isolated")
require(authSessionStore.contains("Keep the verified V2 session in-process only."), "QA auth fallback must remain in-process only")
require(releaseRegression.contains("RUN_DIGITAL_HUMAN_RUNTIME_STUB_GATE"), "release regression optional runtime stub gate is missing")
require(releaseRegression.contains("run-digital-human-runtime-stub-smoke.sh"), "release regression must call runtime stub smoke")

require(statusDoc.contains("TENCENT_DIGITAL_HUMAN_APP_KEY"), "status doc should use Tencent appkey env")
require(statusDoc.contains("TENCENT_DIGITAL_HUMAN_ACCESS_TOKEN"), "status doc should use Tencent accesstoken env")
require(statusDoc.contains("asset_virtualman_key"), "status doc should document official asset_virtualman_key")
require(statusDoc.contains("virtualman_project_id"), "status doc should document official virtualman_project_id")
require(statusDoc.contains("ASR-only"), "status doc should mark SecretId/SecretKey/AppId as ASR-only")

print("digital-human-session-client-check passed")
